apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-app
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-options: CreateNamespace=true
spec:
  project: default
  source:
    repoURL: https://github.com/rajeshreddy185/Devops-Linux
    targetRevision: master
    path: Helm-to-ArgoCd/updated_yaml
    helm:
      releaseName: hello-app
      valueFiles:
      - values.yaml
      parameters:
      - name: replicaCount
        value: "1"
      - name: strategy.type
        value: RollingUpdate
      - name: strategy.rollingUpdate.maxSurge
        value: "25%"
      - name: strategy.rollingUpdate.maxUnavailable
        value: "25%"
      skipCrds: true
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    - RespectIgnoreDifferences=true
    - ApplyOutOfSyncOnly=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  ignoreDifferences:
  - group: apps
    kind: Deployment
    jsonPointers:
    - /spec/replicas
    - /spec/selector
    - /spec/template/metadata/annotations
    - /metadata/labels/app.kubernetes.io/instance
    - /metadata/labels/app.kubernetes.io/name
    - /metadata/labels/app.kubernetes.io/managed-by
    - /metadata/labels/helm.sh/chart
  - group: ""
    kind: Service
    jsonPointers:
    - /metadata/labels/app.kubernetes.io/instance
    - /metadata/labels/app.kubernetes.io/name
    - /metadata/labels/app.kubernetes.io/managed-by
    - /metadata/labels/helm.sh/chart
